import type { Song } from "./songs";

/**
 * Beginner chord versions of well-known English-language songs.
 *
 * These are practice charts, not transcriptions: the common simplified
 * progression, in a key a beginner can hold down. Keys, voicings and section
 * structures vary between recordings and between published versions, so check
 * anything here against the record before treating it as definitive.
 */

const ALL_PURPOSE = "D · D U · U D U";
const SIMPLE = "D · D · D · D";
const BALLAD = "D · D U · D · D U";
const PICKED = "Arpeggio — pick the strings one at a time";
const ROCK = "All downstrokes, palm muted";
const SIXTEENTHS = "1 e and a — keep the hand moving";

const uniq = (chords: string[]) => [...new Set(chords)];

interface Opts {
  loop?: string[];
  chords?: string[];
  capo?: number;
  strum?: string;
  bpm?: number;
  note?: string;
  planDay?: number;
}

const S = (
  id: string,
  title: string,
  artist: string,
  difficulty: 1 | 2 | 3,
  teaches: string,
  o: Opts = {},
): Song => ({
  id,
  title,
  artist,
  language: "english",
  difficulty,
  teaches,
  loop: o.loop ?? [],
  chords: o.chords ?? uniq(o.loop ?? []),
  capo: o.capo,
  strum: o.strum,
  bpm: o.bpm,
  note: o.note,
  planDay: o.planDay,
});

export const ENGLISH_SONGS: Song[] = [
  /* ---- riffs from the plan ---- */
  S("smoke-on-the-water", "Smoke on the Water", "Deep Purple", 1,
    "Single-note riff picking on one string. The classic first riff.",
    { planDay: 1, note: "All on the D string. The playable tab is on day 1 of your plan." }),
  S("seven-nation-army", "Seven Nation Army", "The White Stripes", 1,
    "Seven notes on one string, plus sliding your hand along the neck.",
    { planDay: 5, note: "Playable tab on day 5 of your plan." }),
  S("iron-man", "Iron Man", "Black Sabbath", 1,
    "Moving power chords slowly and heavily. Your first full riff song.",
    { loop: ["B5", "D5", "E5", "D5"], strum: ROCK, bpm: 60, planDay: 11 }),
  S("back-in-black", "Back in Black", "AC/DC", 1,
    "Groove and silence — stopping the strings is the whole trick.",
    { loop: ["E5", "D5", "A5", "E5"], strum: "Open and ringing, with real silence between", bpm: 60, planDay: 13 }),
  S("teen-spirit", "Smells Like Teen Spirit", "Nirvana", 1,
    "Four power chords, two shapes, moving up three frets.",
    { loop: ["F5", "Bb5", "Ab5", "Db5"], strum: ROCK, bpm: 70, planDay: 12,
      note: "Ab5 is low E fret 4, Db5 is A string fret 4 — the same two shapes moved up." }),
  S("enter-sandman", "Enter Sandman", "Metallica", 2,
    "Palm-muted chugging and tight downpicking.",
    { chords: ["E5"], planDay: 41, note: "A chug-and-fill drill in this style is on day 41." }),

  /* ---- four-chord classics ---- */
  S("zombie", "Zombie", "The Cranberries", 1,
    "Four open chords, one strum pattern, whole song. A great first full song.",
    { loop: ["Em", "C", "G", "D"], strum: ALL_PURPOSE, bpm: 70, planDay: 17 }),
  S("boulevard", "Boulevard of Broken Dreams", "Green Day", 1,
    "Steady strumming across four chords.",
    { loop: ["Em", "G", "D", "A"], strum: ALL_PURPOSE, bpm: 80, planDay: 18,
      note: "The record sits a semitone away, so these shapes sound right alone but won't match it exactly." }),
  S("knockin", "Knockin' on Heaven's Door", "Bob Dylan", 1,
    "Slow, forgiving changes. Learn it while chords still feel hard.",
    { loop: ["G", "D", "Am", "G", "D", "C"], strum: SIMPLE, bpm: 65 }),
  S("let-it-be", "Let It Be", "The Beatles", 1,
    "The four-chord backbone of popular music.",
    { loop: ["C", "G", "Am", "F"], strum: ALL_PURPOSE, bpm: 70, note: "Use Fmaj7 in place of F until the barre is ready." }),
  S("no-woman-no-cry", "No Woman No Cry", "Bob Marley", 1,
    "Relaxed reggae feel — the emphasis sits off the beat.",
    { loop: ["C", "G", "Am", "F"], strum: "Accent the upstrokes", bpm: 76 }),
  S("stand-by-me", "Stand By Me", "Ben E. King", 1,
    "A four-chord loop that never changes. Ideal for locking in timing.",
    { loop: ["G", "Em", "C", "D"], strum: SIMPLE, bpm: 60 }),
  S("country-roads", "Take Me Home, Country Roads", "John Denver", 1,
    "Clean major-chord changes at a walking pace.",
    { loop: ["G", "Em", "D", "C"], strum: ALL_PURPOSE, bpm: 82 }),
  S("three-little-birds", "Three Little Birds", "Bob Marley", 1,
    "Three chords, endlessly cheerful. Good for a first singalong.",
    { loop: ["A", "D", "A", "E"], strum: "Accent the upstrokes", bpm: 76 }),
  S("redemption-song", "Redemption Song", "Bob Marley", 1,
    "Gentle strumming with space between chords.",
    { loop: ["G", "Em", "C", "D"], strum: ALL_PURPOSE, bpm: 74 }),
  S("imagine", "Imagine", "John Lennon", 1,
    "Slow changes and a very exposed right hand.",
    { loop: ["C", "F", "C", "G"], strum: SIMPLE, bpm: 70 }),
  S("riptide", "Riptide", "Vance Joy", 1,
    "Three chords and a driving strum. Very hard to get wrong.",
    { loop: ["Am", "G", "C", "C"], strum: ALL_PURPOSE, bpm: 90 }),
  S("im-yours", "I'm Yours", "Jason Mraz", 1,
    "The four-chord loop with a bouncy, off-beat strum.",
    { loop: ["G", "D", "Em", "C"], strum: "Accent the upstrokes", bpm: 76 }),
  S("wonderwall", "Wonderwall", "Oasis", 1,
    "Capo use and a relentless strum pattern.",
    { loop: ["Em", "G", "D", "A"], capo: 2, strum: ALL_PURPOSE, bpm: 80,
      note: "Commonly capo 2. The full version uses Em7 and A7sus4 voicings; these simpler shapes work." }),
  S("perfect", "Perfect", "Ed Sheeran", 1,
    "Slow swaying strumming and clean changes.",
    { loop: ["G", "Em", "C", "D"], strum: BALLAD, bpm: 63 }),
  S("photograph", "Photograph", "Ed Sheeran", 1,
    "Holding a steady pattern under a melody.",
    { loop: ["G", "D", "Em", "C"], capo: 1, strum: BALLAD, bpm: 66 }),
  S("thinking-out-loud", "Thinking Out Loud", "Ed Sheeran", 2,
    "Groove and small fills between chords.",
    { loop: ["D", "G", "A", "D"], strum: "D · D U · U D U with dead strums", bpm: 79 }),
  S("shape-of-you", "Shape of You", "Ed Sheeran", 1,
    "A tight, percussive loop. Rhythm matters more than the chords here.",
    { loop: ["Am", "Dm", "G", "C"], strum: SIXTEENTHS, bpm: 96 }),
  S("someone-like-you", "Someone Like You", "Adele", 2,
    "Arpeggio picking held steady under a vocal.",
    { loop: ["G", "D", "Em", "C"], capo: 2, strum: PICKED, bpm: 68 }),
  S("chasing-cars", "Chasing Cars", "Snow Patrol", 1,
    "Four chords, picked then strummed. A lesson in building intensity.",
    { loop: ["A", "E", "D", "A"], strum: PICKED, bpm: 104 }),
  S("counting-stars", "Counting Stars", "OneRepublic", 1,
    "Driving sixteenth strumming on a repeating loop.",
    { loop: ["Am", "C", "G", "F"], strum: SIXTEENTHS, bpm: 108 }),
  S("demons", "Demons", "Imagine Dragons", 1,
    "Four chords with dynamics — quiet verse, loud chorus.",
    { loop: ["C", "G", "Am", "F"], strum: ALL_PURPOSE, bpm: 90 }),
  S("radioactive", "Radioactive", "Imagine Dragons", 1,
    "Heavy, deliberate strumming with plenty of space.",
    { loop: ["Am", "C", "G", "G"], strum: SIMPLE, bpm: 68 }),
  S("believer", "Believer", "Imagine Dragons", 2,
    "Percussive, aggressive rhythm playing.",
    { loop: ["Am", "F", "C", "G"], strum: "Hard downstrokes with muted clicks", bpm: 125 }),
  S("viva-la-vida", "Viva La Vida", "Coldplay", 1,
    "A four-chord cycle that keeps lifting. Good for strum dynamics.",
    { loop: ["C", "D", "G", "Em"], strum: SIMPLE, bpm: 69 }),
  S("yellow", "Yellow", "Coldplay", 1,
    "Simple shapes with a capo, and a lot of ringing open strings.",
    { loop: ["G", "D", "C", "G"], capo: 4, strum: ALL_PURPOSE, bpm: 87 }),
  S("fix-you", "Fix You", "Coldplay", 2,
    "Sustained chords and a long, patient build.",
    { loop: ["C", "G", "Am", "F"], strum: PICKED, bpm: 69 }),
  S("the-scientist", "The Scientist", "Coldplay", 2,
    "Slow arpeggios with an unusual, sad turn in the progression.",
    { loop: ["Dm", "Bb", "F", "C"], strum: PICKED, bpm: 73 }),
  S("ho-hey", "Ho Hey", "The Lumineers", 1,
    "Two chords for most of it. Almost impossible to get lost in.",
    { loop: ["C", "F", "C", "G"], strum: SIMPLE, bpm: 80 }),
  S("hey-there-delilah", "Hey There Delilah", "Plain White T's", 2,
    "Fingerpicked pattern held under a melody.",
    { loop: ["D", "A", "Bm", "G"], strum: PICKED, bpm: 104 }),
  S("wagon-wheel", "Wagon Wheel", "Old Crow Medicine Show", 1,
    "The classic four-chord country cycle at a good clip.",
    { loop: ["G", "D", "Em", "C"], strum: ALL_PURPOSE, bpm: 76 }),
  S("free-fallin", "Free Fallin'", "Tom Petty", 1,
    "Two chords and a signature ringing high note.",
    { loop: ["D", "A", "D", "A"], capo: 3, strum: ALL_PURPOSE, bpm: 84 }),
  S("sweet-home-alabama", "Sweet Home Alabama", "Lynyrd Skynyrd", 2,
    "A three-chord loop with fills between changes.",
    { loop: ["D", "C", "G", "G"], strum: ALL_PURPOSE, bpm: 98 }),
  S("highway-to-hell", "Highway to Hell", "AC/DC", 1,
    "Open chords played like power chords — hard, short, confident.",
    { loop: ["A", "D", "G", "D"], strum: "Hard downstrokes with gaps", bpm: 116 }),
  S("californication", "Californication", "Red Hot Chili Peppers", 2,
    "Clean tone, restraint, and a very exposed picking hand.",
    { loop: ["Am", "F", "C", "G"], strum: PICKED, bpm: 96 }),
  S("wonderful-tonight", "Wonderful Tonight", "Eric Clapton", 2,
    "Slow, spacious changes and room for small lead fills.",
    { loop: ["G", "D", "C", "D"], strum: SIMPLE, bpm: 66 }),
  S("hallelujah", "Hallelujah", "Leonard Cohen", 2,
    "A picked 6/8 feel across a long, unhurried progression.",
    { loop: ["C", "Am", "C", "Am", "F", "G", "C", "C"], strum: PICKED, bpm: 60 }),
  S("wish-you-were-here", "Wish You Were Here", "Pink Floyd", 2,
    "Fingerpicking with hammer-ons on open strings.",
    { loop: ["Em", "G", "Em", "G", "C", "D", "Am", "Am"], strum: PICKED, bpm: 60 }),
  S("nothing-else-matters", "Nothing Else Matters", "Metallica", 2,
    "Fingerpicked arpeggios on open strings, then full chords.",
    { loop: ["Em", "D", "C", "Em"], strum: PICKED, bpm: 55,
      note: "The intro is picked one note at a time. A good target once week 4 is done." }),
  S("creep", "Creep", "Radiohead", 2,
    "Four chords and one very satisfying loud strum.",
    { loop: ["G", "B", "C", "Cm"], strum: "Quiet, then all-out on the change", bpm: 92,
      note: "B and Cm need barre shapes — a good week-6 target." }),
  S("come-as-you-are", "Come As You Are", "Nirvana", 2,
    "A repeating low riff under a simple vocal.",
    { chords: ["E5", "A5"], note: "Built on a low single-note figure rather than strummed chords." }),
  S("sunshine-of-your-love", "Sunshine of Your Love", "Cream", 2,
    "A blues-scale riff in double stops. Great pentatonic practice.",
    { chords: ["D5", "C5", "G5"], note: "Built from the minor pentatonic shape you learn in week 5." }),
  S("sweet-child", "Sweet Child O' Mine", "Guns N' Roses", 3,
    "Fast, accurate string-skipping in the intro. A real test.",
    { loop: ["D", "C", "G", "D"], strum: SIMPLE, bpm: 62,
      note: "The chords are easy; the intro riff is not. Learn it at half speed." }),
  S("hotel-california", "Hotel California", "Eagles", 3,
    "Eight barre-heavy changes in a row. The best arpeggio workout on this list.",
    { loop: ["Bm", "F#", "A", "E", "G", "D", "Em", "F#"], strum: PICKED, bpm: 74,
      note: "Eight different chords, three of them barres — this is a week-8 target, not a week-3 one. Play it at 50bpm before you try 74." }),
  S("stairway", "Stairway to Heaven", "Led Zeppelin", 3,
    "Fingerpicked melody and bass at once. A months-long project.",
    { chords: ["Am", "C", "D", "Fmaj7", "G"],
      note: "A picked arrangement rather than a strummed progression. Don't make it your first fingerpicking song." }),
  S("blackbird", "Blackbird", "The Beatles", 3,
    "Thumb and fingers moving independently. The classic next step after week 8.",
    { chords: ["G", "Am", "C", "D"], note: "Fingerstyle throughout — melody and bass together." }),
];
